version: "0.2"
language: en, es
files:
  - /**/*.{tsx,ts,js,jsx,json}
ignorePaths:
  - /**/*.cert
  - package.json
  - /**/*.config.{js,json,yaml,yml,toml}
  - /**/*lock.{json,yaml,yml}
  - /**/*.xml
  - /**/*.{sass,scss,css}
  - /**/*.svg
  - /public/manifest.json
dictionaryDefinitions:
  - name: spanish
    path: ./node_modules/@cspell/dict-es-es/Spanish.trie.gz
dictionaries:
  - spanish
  - companies
  - softwareTerms
  - fonts
  - npm
  - misc
words:
  - antd
  - atrule
  - BSON
  - camelcase
  - capath
  - chartjs
  - darch
  - desaturate
  - endregion
  - esnext
  - formik
  - Formik
  - headlessui
  - heroicons
  - indianred
  - isequal
  - isplainobject
  - jedec
  - lightgray
  - listitem
  - mediumseagreen
  - msapplication
  - popperjs
  - recaptcha
  - royalblue
  - solarwind
  - stratego
  - swind
  - tailwindcss
  - timetravel
  - trojan
  - unmarshall
  - volta
  - wysiwyg
